### ISSUE TITLE
So, I've had time to look at this again, and it still doesn't work - as I said initially, I am changing the participant's scene dynamically, so the old buttons aren't there, and the new buttons appear. But using updateControls just means that I get the error "unknown control id specified"

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#118]
So, I've had time to look at this again, and it still doesn't work - as I said initially, I am changing the participant's scene dynamically, so the old buttons aren't there, and the new buttons appear. But using updateControls just means that I get the error "unknown control id specified"

Which... makes sense? Cuz the old control isn't there. And I just added a new control. How do I achieve modifications of existing scenes if updateControls only changes existing controls, and if updateScenes isn't suitable?

_Originally posted by @djarcas in https://github.com/mixer/interactive-unity-plugin/issue_comments#issuecomment-452646063_

**Comment by rasterknight** [comment]
Hi @djarcas , thx for posting.
Same here for now reading from all you posted and same experience here: im taking the route of:
only using groups, scenes are precreated and are only IDS so that giveInput works from ParticipantView.
And I manage myself sending messages to Participant to switch views themselves when they move around in the groups or in game states.
At least thats my plan for my next test.

**Comment by payzer** [comment]
If you get unknown control id then that means you have to create the controls, then update them. But list rasterknight said, I usually do the same thing: 1) Create controls, then 2) update them.
