### ISSUE TITLE
Chat support?

### ISSUE THREAD

**Issue by djarcas** [mixer/interactive-unity-plugin#123]
Does the Unity Plugin allow me to send messages to the chat? I can't find any documentation one way or the other, and the 'chat-unity' demo doesn't seem to work anymore.

**Comment by payzer** [comment]
It doesn't at the moment. Specifically, the scope you need to request is different.

**Comment by djarcas** [comment]
Er. I'm not really sure what that sentence, means, I'm afraid.

**Comment by payzer** [comment]
Sorry! More words :)

The historical reason why the Unity plugin hasn't supported chat is because they interactive and chat required different access scopes (the dialog that says "allow Mixer to access your..." has more and different things for chat).

I'm planning on giving the Unity chat sample a look tomorrow (Monday) to see what's going on. It used to work, but there have been changes to chat so I'll try to figure out if I need to modify and re-post it.

**Comment by djarcas** [comment]
I'll hold fire trying to implement it myself then :-) :+1:

**Comment by payzer** [comment]
I tried myself this morning and got the same result as you (UACCESS error). I'm going to ask our chat engineers and I'll update this issue when I hear back. Note: It's snowing hard in the offices over here so there might be some delay.

**Comment by djarcas** [comment]
...it's snowing IN the offices? You guys should invest in a roof.

**Comment by payzer** [comment]
Hahaha. I knew investing in an "open office plan" would backfire on a snow day. We'll have to install a roof :)

**Comment by payzer** [comment]
It works. You need to make sure you aren't in test stream mode. The problem is the chat sample connects anonymously and if you are in test stream mode you don't have access. If you connect with auth, probably different story. But at least for the sample purposes, I just tried turning off test stream mode and then connected.

I'll update the docs to call that out.
