### ISSUE TITLE
UWP crash on GoInteractive

### ISSUE THREAD

**Issue by payzer** [mixer/interactive-unity-plugin#21]
The sample works, but we found a game where calling GoInteractive causes a native exception for the UWP build.

We are investigating. We will update with status as we have status.

**Comment by TimeWarDoctor** [comment]
I notice this happens when attempting to create a plugin that references the Microsoft.Mixer plugin.  I built an UWP plugin with a MonoBehavior class that uses the Microsoft.Mixer namespace, and included the MixerInteraction and related classes from the mixer plugin's scripts folder.  Although my plugin builds fine in Visual Studio, and imports fine into Unity3D, when I attempt to add my MonoBehavior component with Mixer functionality to any GameObject, my Unity3D editor crashes.

I assume this is another symptom of this issue but if I am doing something wrong, please let me know.

Thanks!

**Comment by payzer** [comment]
I think this is something else. This crash only occurs: (1) at runtime, (2) on an Xbox and (3) only for some games. If you are seeing a crash in the editor it would be something else.

The crash is in the Editor? If so, it would be something else.

**Comment by TimeWarDoctor** [comment]
Yes...the crash is in the editor...once I add my component that has Mixer functionality to any GameObject, the Unity editor shuts down.

What namespaces should I use in my plugin?  What assemblies should I reference?  Do I need to pull in the scripts for the MixerInteractive class or not?

**Comment by payzer** [comment]
Does it have details in the exception? It could be not referencing the right DLL. There are different mixer dlls per platform. So there's one for UWP and a different one for the Editor. That might be it.

**Comment by TimeWarDoctor** [comment]
No exception thrown.  The editor just suddenly crashes.  Sorry.  I'll try referencing the editor one to see if that fixes the issue.

But should I be including the MixerInteractive script in my plugin (ie compiling it)?

**Comment by TimeWarDoctor** [comment]
Your suggestions worked like a charm.  I referenced the editor DLL instead and was able to attach the component to a game object.
But what happens when I want to run the game on another UWP device?  Do I have to change the reference and rebuild my library, then re-import it into Unity3D?
Or does Unity3D automatically change that reference to the Mixer plugin UWP DLL reference?

**Comment by payzer** [comment]
Unity isn't quite magic. The way it works is if you have multiple platforms, you may need more than one DLL. For instance, In Unity you mark each DLL for the platforms it applies for. You do that in the inspector for the DLL. If you link against one of the Mixer DLLs, then yes you would need to create separate DLLs even if your DLL runs on each platform. The big problem is there are ifdefs in the MixerInteractive script so I'll bet Visual Studio will only compile the relevant code for each platform into your DLL.

**Comment by payzer** [comment]
We've been unable to repro the original issue so we'll close this bug for now, but will open a new issue if we get a solid repro.

**Comment by payzer** [comment]
By original issue, we mean a crash when trying to go interactive, not the visual studio build issue.
