### ISSUE TITLE
After calling MixerInteractive.GoInteractive, State gets stuck at "Initializing"

### ISSUE THREAD

**Issue by crazylune** [mixer/interactive-unity-plugin#36]
I'm not sure if that's a service or client issue, but I call the same simple steps found in the tutorial here (which boils down to MixerInteractive.GoInteractive) and added an EventHandler for OnInteractivityStateChanged.

For some reason, the MixerInteractive item will randomly (most of the time) wait forever after showing these state changes:

- NotInitialized
- NotInitialized
- Initializing
Then I can wait 5 minutes and nothing happens.

By killing/pressing play several times in a row, I will sometimes get it to Initialize and work properly.  After that first success, it's mostly stable, but it's sadly frustrating when trying to develop a game...

Maybe I'm doing something wrong, but it feels like a bug to me.
Thanks,
-Sam

**Comment by payzer** [comment]
Sorry for the delayed response. On this date we were experiencing service issues (that have now been fixed). Are you still experiencing this issue?

**Comment by samdes-ms** [comment]
Thanks for the reply, I must admit that I've been hitting this less and less lately. 

Follow-up: when we get stuck in that "Initializing" state for a while (20+ sec), is it 100% certain to be Mixer Service issue or are there other possible causes for this problem?

I'm only asking because the documentation + the returned state message aren't explicit at all, and this leads us to believe our application is doing something wrong. 

Maybe the resolution for this issue would be as simple as updating the Doc online, or having the UnityPlugin be a bit more verbose about what is going on with every state it can return?

**Comment by payzer** [comment]
Thank you for the feedback, we are going to be investing in much better error messages over the next couple months in the Unity SDK. In the meantime, we've created the troubleshooting guide here: https://github.com/mixer/interactive-unity-plugin/wiki/Troubleshooting-guide 
The guide covers some of the common issues.

**Comment by payzer** [comment]
I'll leave this issue open and resolve it once we have better error messaging in the SDK.

**Comment by samdes-ms** [comment]
Thanks for the extra troubleshooting doc, that may come in handy.

**Comment by payzer** [comment]
We now have much better error messaging in the SDK so we're going to go ahead and close the issue. Thank you for opening it!
