### ISSUE TITLE
Missing WebSocketSharp reference

### ISSUE THREAD

**Issue by tencircles** [mixer/interactive-unity-plugin#64]
Running on unity v2017.4.0f1 on OSX v10.13.3. 

After adding this plugin I get the following error and the project will not compile or run.

````
Assets/MixerInteractive/Source/Scripts/InteractivityManager.cs(47,7): error CS0246: The type or namespace name `WebSocketSharp' could not be found. Are you missing an assembly reference?
````

Any ideas what's going on here?

**Comment by payzer** [comment]
Thank you for filing this issue.

That means it's not finding the websocketsharp.dll. This is probably because the dll isn't marked for inclusion for OSX. The websocketsharp dlls are in the DLLs folder. Double check the checkboxes in the inspector. We probably have a bug on our side for OSX builds. I apologize that you ran into this.

We'll have one of our developers look at this issue tomorrow.

**Comment by Francisobiagwu** [comment]
I am using an older version of Unity and currently experiencing the same issue. Please what is the solution?
